[package]
name = "agsol-glue"
version = "0.0.1"
edition = "2021"

[dependencies]
anyhow = "1.0"
env_logger = "0.9.0"
log = "0.4"
structopt = "0.3"
agsol-borsh-schema = { path = "../agsol-borsh-schema", features = ["full"] }
