name: general code check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  fmt:
    name: formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo fmt -- --check
  test:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -Dwarnings # fails on warnings as well
    steps:
      - uses: actions/checkout@v2
      - name: Set env vars
        run: |
          echo "RUST_NIGHTLY=nightly-2021-12-09" >> $GITHUB_ENV

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_NIGHTLY }}
          override: true
          profile: minimal

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: cargo-build-${{ hashFiles('**/Cargo.lock') }}-${{ env.RUST_NIGHTLY}}

      - name: add-nightly-clippy
        run: rustup component add clippy --toolchain ${{ env.RUST_NIGHTLY }}-x86_64-unknown-linux-gnu

      - name: build
        run: cargo build --color=always --all-features --examples --tests

      - name: clippy
        run: cargo clippy --color=always --all-features --examples --tests

      - name: test-rust
        run: cargo t --color=always --all-features

      - name: test-borsh-js
        run: |
          cd agsol-borsh-schema
          cd test-output
          npm i
          npm install -g ts-node
          ts-node test.ts

      - name: test-wasm-js
        run: |
          cd agsol-wasm-client-test
          wasm-pack build --target nodejs
          cd test-output
          npm i
          npm install -g ts-node
          ts-node test.ts

